/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmadoRouteImport } from './routes/confirmado'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedHogarRouteImport } from './routes/_authenticated/hogar'
import { Route as AuthenticatedHoyRouteImport } from './routes/_authenticated/hoy'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCronDispatchRouteImport } from './routes/api/cron/dispatch'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api/push/unsubscribe'
import { Route as ApiV1GuideRouteImport } from './routes/api/v1/guide'
import { Route as ApiV1AccountDeleteRouteImport } from './routes/api/v1/account/delete'
import { Route as ApiV1HouseholdSyncRouteImport } from './routes/api/v1/household/sync'
import { Route as ApiV1OnboardingParseRouteImport } from './routes/api/v1/onboarding/parse'
import { Route as ApiV1PlanAdjustRouteImport } from './routes/api/v1/plan/adjust'
import { Route as ApiV1PlanConfirmRouteImport } from './routes/api/v1/plan/confirm'
import { Route as ApiV1PlanGenerateRouteImport } from './routes/api/v1/plan/generate'
import { Route as ApiV1PlanGoalImpactRouteImport } from './routes/api/v1/plan/goal-impact'
import { Route as ApiV1PlanMealRouteImport } from './routes/api/v1/plan/meal'
import { Route as ApiV1PlanShoppingOwnedRouteImport } from './routes/api/v1/plan/shopping-owned'
import { Route as ApiV1PlanTripActualRouteImport } from './routes/api/v1/plan/trip-actual'
import { Route as ApiV1PlanWelcomeRouteImport } from './routes/api/v1/plan/welcome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmadoRoute = ConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHogarRoute = AuthenticatedHogarRouteImport.update({
  id: '/hogar',
  path: '/hogar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHoyRoute = AuthenticatedHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDispatchRoute = ApiCronDispatchRouteImport.update({
  id: '/api/cron/dispatch',
  path: '/api/cron/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GuideRoute = ApiV1GuideRouteImport.update({
  id: '/api/v1/guide',
  path: '/api/v1/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountDeleteRoute = ApiV1AccountDeleteRouteImport.update({
  id: '/api/v1/account/delete',
  path: '/api/v1/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HouseholdSyncRoute = ApiV1HouseholdSyncRouteImport.update({
  id: '/api/v1/household/sync',
  path: '/api/v1/household/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OnboardingParseRoute = ApiV1OnboardingParseRouteImport.update({
  id: '/api/v1/onboarding/parse',
  path: '/api/v1/onboarding/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanAdjustRoute = ApiV1PlanAdjustRouteImport.update({
  id: '/api/v1/plan/adjust',
  path: '/api/v1/plan/adjust',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanConfirmRoute = ApiV1PlanConfirmRouteImport.update({
  id: '/api/v1/plan/confirm',
  path: '/api/v1/plan/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanGenerateRoute = ApiV1PlanGenerateRouteImport.update({
  id: '/api/v1/plan/generate',
  path: '/api/v1/plan/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanGoalImpactRoute = ApiV1PlanGoalImpactRouteImport.update({
  id: '/api/v1/plan/goal-impact',
  path: '/api/v1/plan/goal-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanMealRoute = ApiV1PlanMealRouteImport.update({
  id: '/api/v1/plan/meal',
  path: '/api/v1/plan/meal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanShoppingOwnedRoute = ApiV1PlanShoppingOwnedRouteImport.update({
  id: '/api/v1/plan/shopping-owned',
  path: '/api/v1/plan/shopping-owned',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanTripActualRoute = ApiV1PlanTripActualRouteImport.update({
  id: '/api/v1/plan/trip-actual',
  path: '/api/v1/plan/trip-actual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlanWelcomeRoute = ApiV1PlanWelcomeRouteImport.update({
  id: '/api/v1/plan/welcome',
  path: '/api/v1/plan/welcome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/restablecer': typeof RestablecerRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/hogar': typeof AuthenticatedHogarRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cron/dispatch': typeof ApiCronDispatchRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/v1/guide': typeof ApiV1GuideRoute
  '/api/v1/account/delete': typeof ApiV1AccountDeleteRoute
  '/api/v1/household/sync': typeof ApiV1HouseholdSyncRoute
  '/api/v1/onboarding/parse': typeof ApiV1OnboardingParseRoute
  '/api/v1/plan/adjust': typeof ApiV1PlanAdjustRoute
  '/api/v1/plan/confirm': typeof ApiV1PlanConfirmRoute
  '/api/v1/plan/generate': typeof ApiV1PlanGenerateRoute
  '/api/v1/plan/goal-impact': typeof ApiV1PlanGoalImpactRoute
  '/api/v1/plan/meal': typeof ApiV1PlanMealRoute
  '/api/v1/plan/shopping-owned': typeof ApiV1PlanShoppingOwnedRoute
  '/api/v1/plan/trip-actual': typeof ApiV1PlanTripActualRoute
  '/api/v1/plan/welcome': typeof ApiV1PlanWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/restablecer': typeof RestablecerRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/hogar': typeof AuthenticatedHogarRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cron/dispatch': typeof ApiCronDispatchRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/v1/guide': typeof ApiV1GuideRoute
  '/api/v1/account/delete': typeof ApiV1AccountDeleteRoute
  '/api/v1/household/sync': typeof ApiV1HouseholdSyncRoute
  '/api/v1/onboarding/parse': typeof ApiV1OnboardingParseRoute
  '/api/v1/plan/adjust': typeof ApiV1PlanAdjustRoute
  '/api/v1/plan/confirm': typeof ApiV1PlanConfirmRoute
  '/api/v1/plan/generate': typeof ApiV1PlanGenerateRoute
  '/api/v1/plan/goal-impact': typeof ApiV1PlanGoalImpactRoute
  '/api/v1/plan/meal': typeof ApiV1PlanMealRoute
  '/api/v1/plan/shopping-owned': typeof ApiV1PlanShoppingOwnedRoute
  '/api/v1/plan/trip-actual': typeof ApiV1PlanTripActualRoute
  '/api/v1/plan/welcome': typeof ApiV1PlanWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/restablecer': typeof RestablecerRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/hogar': typeof AuthenticatedHogarRoute
  '/_authenticated/hoy': typeof AuthenticatedHoyRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cron/dispatch': typeof ApiCronDispatchRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/v1/guide': typeof ApiV1GuideRoute
  '/api/v1/account/delete': typeof ApiV1AccountDeleteRoute
  '/api/v1/household/sync': typeof ApiV1HouseholdSyncRoute
  '/api/v1/onboarding/parse': typeof ApiV1OnboardingParseRoute
  '/api/v1/plan/adjust': typeof ApiV1PlanAdjustRoute
  '/api/v1/plan/confirm': typeof ApiV1PlanConfirmRoute
  '/api/v1/plan/generate': typeof ApiV1PlanGenerateRoute
  '/api/v1/plan/goal-impact': typeof ApiV1PlanGoalImpactRoute
  '/api/v1/plan/meal': typeof ApiV1PlanMealRoute
  '/api/v1/plan/shopping-owned': typeof ApiV1PlanShoppingOwnedRoute
  '/api/v1/plan/trip-actual': typeof ApiV1PlanTripActualRoute
  '/api/v1/plan/welcome': typeof ApiV1PlanWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confirmado'
    | '/restablecer'
    | '/ajustes'
    | '/chat'
    | '/historial'
    | '/hogar'
    | '/hoy'
    | '/onboarding'
    | '/perfil'
    | '/plan'
    | '/api/chat'
    | '/api/cron/dispatch'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/v1/guide'
    | '/api/v1/account/delete'
    | '/api/v1/household/sync'
    | '/api/v1/onboarding/parse'
    | '/api/v1/plan/adjust'
    | '/api/v1/plan/confirm'
    | '/api/v1/plan/generate'
    | '/api/v1/plan/goal-impact'
    | '/api/v1/plan/meal'
    | '/api/v1/plan/shopping-owned'
    | '/api/v1/plan/trip-actual'
    | '/api/v1/plan/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confirmado'
    | '/restablecer'
    | '/ajustes'
    | '/chat'
    | '/historial'
    | '/hogar'
    | '/hoy'
    | '/onboarding'
    | '/perfil'
    | '/plan'
    | '/api/chat'
    | '/api/cron/dispatch'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/v1/guide'
    | '/api/v1/account/delete'
    | '/api/v1/household/sync'
    | '/api/v1/onboarding/parse'
    | '/api/v1/plan/adjust'
    | '/api/v1/plan/confirm'
    | '/api/v1/plan/generate'
    | '/api/v1/plan/goal-impact'
    | '/api/v1/plan/meal'
    | '/api/v1/plan/shopping-owned'
    | '/api/v1/plan/trip-actual'
    | '/api/v1/plan/welcome'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confirmado'
    | '/restablecer'
    | '/_authenticated/ajustes'
    | '/_authenticated/chat'
    | '/_authenticated/historial'
    | '/_authenticated/hogar'
    | '/_authenticated/hoy'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/plan'
    | '/api/chat'
    | '/api/cron/dispatch'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/v1/guide'
    | '/api/v1/account/delete'
    | '/api/v1/household/sync'
    | '/api/v1/onboarding/parse'
    | '/api/v1/plan/adjust'
    | '/api/v1/plan/confirm'
    | '/api/v1/plan/generate'
    | '/api/v1/plan/goal-impact'
    | '/api/v1/plan/meal'
    | '/api/v1/plan/shopping-owned'
    | '/api/v1/plan/trip-actual'
    | '/api/v1/plan/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfirmadoRoute: typeof ConfirmadoRoute
  RestablecerRoute: typeof RestablecerRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCronDispatchRoute: typeof ApiCronDispatchRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
  ApiV1GuideRoute: typeof ApiV1GuideRoute
  ApiV1AccountDeleteRoute: typeof ApiV1AccountDeleteRoute
  ApiV1HouseholdSyncRoute: typeof ApiV1HouseholdSyncRoute
  ApiV1OnboardingParseRoute: typeof ApiV1OnboardingParseRoute
  ApiV1PlanAdjustRoute: typeof ApiV1PlanAdjustRoute
  ApiV1PlanConfirmRoute: typeof ApiV1PlanConfirmRoute
  ApiV1PlanGenerateRoute: typeof ApiV1PlanGenerateRoute
  ApiV1PlanGoalImpactRoute: typeof ApiV1PlanGoalImpactRoute
  ApiV1PlanMealRoute: typeof ApiV1PlanMealRoute
  ApiV1PlanShoppingOwnedRoute: typeof ApiV1PlanShoppingOwnedRoute
  ApiV1PlanTripActualRoute: typeof ApiV1PlanTripActualRoute
  ApiV1PlanWelcomeRoute: typeof ApiV1PlanWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmado': {
      id: '/confirmado'
      path: '/confirmado'
      fullPath: '/confirmado'
      preLoaderRoute: typeof ConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hogar': {
      id: '/_authenticated/hogar'
      path: '/hogar'
      fullPath: '/hogar'
      preLoaderRoute: typeof AuthenticatedHogarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoy': {
      id: '/_authenticated/hoy'
      path: '/hoy'
      fullPath: '/hoy'
      preLoaderRoute: typeof AuthenticatedHoyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/dispatch': {
      id: '/api/cron/dispatch'
      path: '/api/cron/dispatch'
      fullPath: '/api/cron/dispatch'
      preLoaderRoute: typeof ApiCronDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/guide': {
      id: '/api/v1/guide'
      path: '/api/v1/guide'
      fullPath: '/api/v1/guide'
      preLoaderRoute: typeof ApiV1GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/account/delete': {
      id: '/api/v1/account/delete'
      path: '/api/v1/account/delete'
      fullPath: '/api/v1/account/delete'
      preLoaderRoute: typeof ApiV1AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/household/sync': {
      id: '/api/v1/household/sync'
      path: '/api/v1/household/sync'
      fullPath: '/api/v1/household/sync'
      preLoaderRoute: typeof ApiV1HouseholdSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/onboarding/parse': {
      id: '/api/v1/onboarding/parse'
      path: '/api/v1/onboarding/parse'
      fullPath: '/api/v1/onboarding/parse'
      preLoaderRoute: typeof ApiV1OnboardingParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/adjust': {
      id: '/api/v1/plan/adjust'
      path: '/api/v1/plan/adjust'
      fullPath: '/api/v1/plan/adjust'
      preLoaderRoute: typeof ApiV1PlanAdjustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/confirm': {
      id: '/api/v1/plan/confirm'
      path: '/api/v1/plan/confirm'
      fullPath: '/api/v1/plan/confirm'
      preLoaderRoute: typeof ApiV1PlanConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/generate': {
      id: '/api/v1/plan/generate'
      path: '/api/v1/plan/generate'
      fullPath: '/api/v1/plan/generate'
      preLoaderRoute: typeof ApiV1PlanGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/goal-impact': {
      id: '/api/v1/plan/goal-impact'
      path: '/api/v1/plan/goal-impact'
      fullPath: '/api/v1/plan/goal-impact'
      preLoaderRoute: typeof ApiV1PlanGoalImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/meal': {
      id: '/api/v1/plan/meal'
      path: '/api/v1/plan/meal'
      fullPath: '/api/v1/plan/meal'
      preLoaderRoute: typeof ApiV1PlanMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/shopping-owned': {
      id: '/api/v1/plan/shopping-owned'
      path: '/api/v1/plan/shopping-owned'
      fullPath: '/api/v1/plan/shopping-owned'
      preLoaderRoute: typeof ApiV1PlanShoppingOwnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/trip-actual': {
      id: '/api/v1/plan/trip-actual'
      path: '/api/v1/plan/trip-actual'
      fullPath: '/api/v1/plan/trip-actual'
      preLoaderRoute: typeof ApiV1PlanTripActualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/plan/welcome': {
      id: '/api/v1/plan/welcome'
      path: '/api/v1/plan/welcome'
      fullPath: '/api/v1/plan/welcome'
      preLoaderRoute: typeof ApiV1PlanWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedHogarRoute: typeof AuthenticatedHogarRoute
  AuthenticatedHoyRoute: typeof AuthenticatedHoyRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedHogarRoute: AuthenticatedHogarRoute,
  AuthenticatedHoyRoute: AuthenticatedHoyRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfirmadoRoute: ConfirmadoRoute,
  RestablecerRoute: RestablecerRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCronDispatchRoute: ApiCronDispatchRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
  ApiV1GuideRoute: ApiV1GuideRoute,
  ApiV1AccountDeleteRoute: ApiV1AccountDeleteRoute,
  ApiV1HouseholdSyncRoute: ApiV1HouseholdSyncRoute,
  ApiV1OnboardingParseRoute: ApiV1OnboardingParseRoute,
  ApiV1PlanAdjustRoute: ApiV1PlanAdjustRoute,
  ApiV1PlanConfirmRoute: ApiV1PlanConfirmRoute,
  ApiV1PlanGenerateRoute: ApiV1PlanGenerateRoute,
  ApiV1PlanGoalImpactRoute: ApiV1PlanGoalImpactRoute,
  ApiV1PlanMealRoute: ApiV1PlanMealRoute,
  ApiV1PlanShoppingOwnedRoute: ApiV1PlanShoppingOwnedRoute,
  ApiV1PlanTripActualRoute: ApiV1PlanTripActualRoute,
  ApiV1PlanWelcomeRoute: ApiV1PlanWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
